In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import class_weight
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [2]:
housedf=pd.read_csv('horse.csv')
housedf.head()

surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0      no  adult         530101.0         38.5   66.0              28.0   
1     yes  adult         534817.0         39.2   88.0              20.0   
2      no  adult         530334.0         38.3   40.0              24.0   
3     yes  young        5290409.0         39.1  164.0              84.0   
4      no  adult         530255.0         37.3  104.0              35.0   

  temp_of_extremities peripheral_pulse mucous_membrane capillary_refill_time  \
0                cool          reduced             NaN            more_3_sec   
1                 NaN              NaN   pale_cyanotic            less_3_sec   
2              normal           normal       pale_pink            less_3_sec   
3                cold           normal   dark_cyanotic            more_3_sec   
4                 NaN              NaN   dark_cyanotic            more_3_sec   

   ... packed_cell_volume total_protein abdomo_appearance abdomo_protein  \
0  ...               45.0           8.4               NaN            NaN   
1  ...               50.0          85.0            cloudy            2.0   
2  ...               33.0           6.7               NaN            NaN   
3  ...               48.0           7.2     serosanguious            5.3   
4  ...               74.0           7.4               NaN            NaN   

      outcome  surgical_lesion lesion_1 lesion_2  lesion_3  cp_data  
0        died               no  11300.0      0.0         0       no  
1  euthanized               no   2208.0      0.0         0       no  
2       lived               no      0.0      0.0         0      yes  
3        died              yes   2208.0      0.0         0      yes  
4        died               no   4300.0      0.0         0       no  

[5 rows x 28 columns]

In [3]:
missing_columns_values = housedf.isnull().sum()
missing_columns_per = (housedf.isnull().sum()/ len(housedf)) * 100
total_missing_values = pd.concat([missing_columns_values, missing_columns_per], axis = 1, keys = ['Missing Values', 'Percentage'])
total_missing_values = total_missing_values.sort_values('Percentage', ascending=False)
total_missing_values.head(20)

Missing Values  Percentage
nasogastric_reflux_ph             246   82.274247
abdomo_protein                    201   67.224080
abdomo_appearance                 168   56.187291
abdomen                           124   41.471572
nasogastric_reflux                109   36.454849
nasogastric_tube                  107   35.785953
rectal_exam_feces                 107   35.785953
peripheral_pulse                   73   24.414716
rectal_temp                        65   21.739130
respiratory_rate                   64   21.404682
temp_of_extremities                61   20.401338
pain                               60   20.066890
abdominal_distention               60   20.066890
mucous_membrane                    52   17.391304
peristalsis                        49   16.387960
total_protein                      38   12.709030
capillary_refill_time              37   12.374582
packed_cell_volume                 35   11.705686
pulse                              30   10.033445
surgical_lesion                     6    2.006689

In [5]:
housedf['outcome'].value_counts()

outcome
lived         176
died           76
euthanized     41
Name: count, dtype: int64

In [6]:
#hadndle missing values
##outcome is the target

In [4]:
numerical_data = housedf.select_dtypes(include = ['int','float'])
categorical_data = housedf.select_dtypes(include = ['object','category'])
for x in numerical_data:
    housedf[x].fillna(np.mean(housedf[x]), inplace = True,)
for x in categorical_data:
    housedf[x].fillna(housedf[x].mode()[0],inplace = True)

missing_columns_values = housedf.isnull().sum()
missing_columns_per = (housedf.isnull().sum()/ len(housedf)) * 100
total_missing_values = pd.concat([missing_columns_values, missing_columns_per], axis = 1, keys = ['Missing Values', 'Percentage'])
total_missing_values = total_missing_values.sort_values('Percentage', ascending=False)
total_missing_values.head(20)

C:\Users\USER\AppData\Local\Temp\ipykernel_8860\399432779.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  housedf[x].fillna(np.mean(housedf[x]), inplace = True,)
C:\Users\USER\AppData\Local\Temp\ipykernel_8860\399432779.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For ex

Missing Values  Percentage
surgery                             0         0.0
age                                 0         0.0
lesion_3                            0         0.0
lesion_2                            0         0.0
lesion_1                            0         0.0
surgical_lesion                     0         0.0
outcome                             0         0.0
abdomo_protein                      0         0.0
abdomo_appearance                   0         0.0
total_protein                       0         0.0
packed_cell_volume                  0         0.0
abdomen                             0         0.0
rectal_exam_feces                   0         0.0
nasogastric_reflux_ph               0         0.0
nasogastric_reflux                  0         0.0
nasogastric_tube                    0         0.0
abdominal_distention                0         0.0
peristalsis                         0         0.0
pain                                0         0.0
capillary_refill_time               0         0.0

In [8]:
missing_columns_values = housedf.isnull().sum()
missing_columns_per = (housedf.isnull().sum()/ len(housedf)) * 100
total_missing_values = pd.concat([missing_columns_values, missing_columns_per], axis = 1, keys = ['Missing Values', 'Percentage'])
total_missing_values = total_missing_values.sort_values('Percentage', ascending=False)
total_missing_values.head(20)

Missing Values  Percentage
surgery                             0         0.0
age                                 0         0.0
lesion_3                            0         0.0
lesion_2                            0         0.0
lesion_1                            0         0.0
surgical_lesion                     0         0.0
outcome                             0         0.0
abdomo_protein                      0         0.0
abdomo_appearance                   0         0.0
total_protein                       0         0.0
packed_cell_volume                  0         0.0
abdomen                             0         0.0
rectal_exam_feces                   0         0.0
nasogastric_reflux_ph               0         0.0
nasogastric_reflux                  0         0.0
nasogastric_tube                    0         0.0
abdominal_distention                0         0.0
peristalsis                         0         0.0
pain                                0         0.0
capillary_refill_time               0         0.0

In [9]:
housedf['outcome'].value_counts()

outcome
lived         182
died           76
euthanized     41
Name: count, dtype: int64

In [5]:
from sklearn.utils import resample
horse_lived=housedf[housedf['outcome']=='lived']
horse_died=housedf[housedf['outcome']=='died']
horse_euthanzed=housedf[housedf['outcome']=='euthanized']
horsedied_sam=resample(horse_died,n_samples=182)
horseuthanized_sam=resample(horse_euthanzed,n_samples=182)
tweetdf=pd.concat([horse_lived,horsedied_sam,horseuthanized_sam],ignore_index=True)
tweetdf=tweetdf.sample(frac=1)
tweetdf['outcome'].value_counts()

outcome
lived         182
died          182
euthanized    182
Name: count, dtype: int64

In [6]:
encoder = LabelEncoder()
categorical_data = housedf.select_dtypes(include=['object','category'])
for x in categorical_data:
    housedf[x] = encoder.fit_transform(housedf[x])
housedf.head()



surgery  age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0        0    0         530101.0         38.5   66.0              28.0   
1        1    0         534817.0         39.2   88.0              20.0   
2        0    0         530334.0         38.3   40.0              24.0   
3        1    1        5290409.0         39.1  164.0              84.0   
4        0    0         530255.0         37.3  104.0              35.0   

   temp_of_extremities  peripheral_pulse  mucous_membrane  \
0                    1                 3                3   
1                    1                 2                4   
2                    2                 2                5   
3                    0                 2                2   
4                    1                 2                2   

   capillary_refill_time  ...  packed_cell_volume  total_protein  \
0                      2  ...                45.0            8.4   
1                      1  ...                50.0           85.0   
2                      1  ...                33.0            6.7   
3                      2  ...                48.0            7.2   
4                      2  ...                74.0            7.4   

   abdomo_appearance  abdomo_protein  outcome  surgical_lesion  lesion_1  \
0                  1        3.054082        0                0   11300.0   
1                  1        2.000000        1                0    2208.0   
2                  1        3.054082        2                0       0.0   
3                  2        5.300000        0                1    2208.0   
4                  1        3.054082        0                0    4300.0   

   lesion_2  lesion_3  cp_data  
0       0.0         0        0  
1       0.0         0        0  
2       0.0         0        1  
3       0.0         0        1  
4       0.0         0        0  

[5 rows x 28 columns]

In [7]:
x=housedf.drop('outcome',axis=1)
y=housedf['outcome']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [31]:
model1=LogisticRegression(solver='lbfgs')
model1.fit(xtrain,ytrain)


c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
pred1=model1.predict(xtest)
print('\nClassification Report',classification_report(ytest,pred1))
print('\nAccuracy Report\n',accuracy_score(ytest,pred1))
print('\nPrecision Report\n',precision_score(ytest,pred1,average='weighted'))
print('\nRecall Report\n',recall_score(ytest,pred1,average='weighted'))
print('\nF1 score Report\n',f1_score(ytest,pred1,average='weighted'))
print('\nConfusion metrix Report\n',confusion_matrix(ytest,pred1))



Classification Report               precision    recall  f1-score   support

           0       0.43      0.16      0.23        19
           1       0.00      0.00      0.00         5
           2       0.62      0.92      0.74        36

    accuracy                           0.60        60
   macro avg       0.35      0.36      0.32        60
weighted avg       0.51      0.60      0.52        60


Accuracy Report
 0.6

Precision Report
 0.5092991913746631

Recall Report
 0.6

F1 score Report
 0.5180207433016423

Confusion metrix Report
 [[ 3  0 16]
 [ 1  0  4]
 [ 3  0 33]]


c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

In [15]:
model2=DecisionTreeClassifier(class_weight='balanced')
model2.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight='balanced')

In [16]:
pred2=model2.predict(xtest)
print('\nClassification Report',classification_report(ytest,pred2))
print('\nAccuracy Report\n',accuracy_score(ytest,pred2))
print('\nPrecision Report\n',precision_score(ytest,pred2,average='weighted'))
print('\nRecall Report\n',recall_score(ytest,pred2,average='weighted'))
print('\nF1 score Report\n',f1_score(ytest,pred2,average='weighted'))
print('\nConfusion metrix Report\n',confusion_matrix(ytest,pred2))


Classification Report               precision    recall  f1-score   support

           0       0.60      0.47      0.53        19
           1       0.25      0.20      0.22         5
           2       0.71      0.81      0.75        36

    accuracy                           0.65        60
   macro avg       0.52      0.49      0.50        60
weighted avg       0.64      0.65      0.64        60


Accuracy Report
 0.65

Precision Report
 0.6352235772357723

Recall Report
 0.65

F1 score Report
 0.6381136292900998

Confusion metrix Report
 [[ 9  0 10]
 [ 2  1  2]
 [ 4  3 29]]


In [16]:
model3=RandomForestClassifier(random_state=42,n_estimators=200)
model3.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=200, random_state=42)

In [17]:
pred3=model3.predict(xtest)
print('\nClassification Report',classification_report(ytest,pred3))
print('\nAccuracy Report\n',accuracy_score(ytest,pred3))
print('\nPrecision Report\n',precision_score(ytest,pred3,average='weighted'))
print('\nRecall Report\n',recall_score(ytest,pred3,average='weighted'))
print('\nF1 score Report\n',f1_score(ytest,pred3,average='weighted'))
print('\nConfusion metrix Report\n',confusion_matrix(ytest,pred3))


Classification Report               precision    recall  f1-score   support

           0       0.93      0.68      0.79        19
           1       0.00      0.00      0.00         5
           2       0.80      1.00      0.89        36

    accuracy                           0.82        60
   macro avg       0.58      0.56      0.56        60
weighted avg       0.77      0.82      0.78        60


Accuracy Report
 0.8166666666666667

Precision Report
 0.7740476190476191

Recall Report
 0.8166666666666667

F1 score Report
 0.7828282828282828

Confusion metrix Report
 [[13  1  5]
 [ 1  0  4]
 [ 0  0 36]]


In [20]:
model4=KNeighborsClassifier(n_jobs=1000,p=10)
model4.fit(xtrain,ytrain)

KNeighborsClassifier(n_jobs=1000, p=10)

In [20]:
pred4=model4.predict(xtest)
print('\nClassification Report',classification_report(ytest,pred4))
print('\nAccuracy Report\n',accuracy_score(ytest,pred4))
print('\nPrecision Report\n',precision_score(ytest,pred4,average='weighted'))
print('\nRecall Report\n',recall_score(ytest,pred4,average='weighted'))
print('\nF1 score Report\n',f1_score(ytest,pred4,average='weighted'))
print('\nConfusion metrix Report\n',confusion_matrix(ytest,pred4))


Classification Report               precision    recall  f1-score   support

           0       0.39      0.37      0.38        19
           1       0.50      0.40      0.44         5
           2       0.66      0.69      0.68        36

    accuracy                           0.57        60
   macro avg       0.52      0.49      0.50        60
weighted avg       0.56      0.57      0.56        60


Accuracy Report
 0.5666666666666667

Precision Report
 0.559551656920078

Recall Report
 0.5666666666666667

F1 score Report
 0.5622622622622622

Confusion metrix Report
 [[ 7  0 12]
 [ 2  2  1]
 [ 9  2 25]]
